#!/bin/bash

wget -P "/usr/local/bin/" "https://github.com/krallin/tini/releases/download/v0.9.0/tini"
chmod +x "/usr/local/bin/tini"

wget -P "/usr/local/bin/" "https://raw.githubusercontent.com/LolHens/docker-tools/master/bin/my_init"
chmod +x "/usr/local/bin/my_init"
mkdir "/etc/my_init.d"

wget -P "/usr/local/bin/" "https://raw.githubusercontent.com/LolHens/docker-tools/master/bin/appfolders"
chmod +x "/usr/local/bin/appfolders"

echo "appfolders link &> /var/log/appfolders.log" > "/etc/my_init.d/link-appfolders"
chmod +x "/etc/my_init.d/link-appfolders"
